-- Insertion des nouvelles fonctionnalités liées aux rendez-vous
INSERT INTO T_FONCTIONNALITE(F_ID, F_CODE, F_LIBELLE) VALUES (nextval('FONCTIONNALITE_SEQ'),'AJOUTER_RENDEZ_VOUS','Ajouter un nouveau rendez-vous');
INSERT INTO T_FONCTIONNALITE(F_ID, F_CODE, F_LIBELLE) VALUES (nextval('FONCTIONNALITE_SEQ'),'CONSULTER_RENDEZ_VOUS','Consulter un rendez-vous');
INSERT INTO T_FONCTIONNALITE(F_ID, F_CODE, F_LIBELLE) VALUES (nextval('FONCTIONNALITE_SEQ'),'MODIFIER_RENDEZ_VOUS','Modifier un rendez-vous');
INSERT INTO T_FONCTIONNALITE(F_ID, F_CODE, F_LIBELLE) VALUES (nextval('FONCTIONNALITE_SEQ'),'SUPPRIMER_RENDEZ_VOUS','Supprimer un rendez-vous');

-- Insertion des données dans la table jointure  T_ROLE_FONCTIONNALITE
INSERT INTO T_ROLE_FONCTIONNALITE(R_ID,F_ID)
SELECT R_ID, F_ID
FROM T_ROLE R1, T_FONCTIONNALITE F1
WHERE R1.R_CODE IN('ADMIN', 'ASSISTANTE_DIRECTION') AND   F1.F_CODE IN('AJOUTER_RENDEZ_VOUS', 'CONSULTER_RENDEZ_VOUS', 'MODIFIER_RENDEZ_VOUS', 'SUPPRIMER_RENDEZ_VOUS');